---
abstract: 'smart command line options processor'
author:
  - 'Kan Fushihara E<lt>kan.fushihara@gmail.comE<gt>'
build_requires:
  Capture::Tiny: 0
  Test::More: 0.98
  Test::Requires: 0
  Try::Tiny: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Smart-Options
no_index:
  directory:
    - inc
provides:
  Smart::Options:
    file: lib/Smart/Options.pm
    version: 0.02
  Smart::Options::Declare:
    file: lib/Smart/Options/Declare.pm
    version: 0
requires:
  Exporter: 0
  List::MoreUtils: 0
  PadWalker: 0
  Text::Table: 0
  perl: 5.010001
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
